### ISSUE TITLE
Http shorthand events is not supported

### ISSUE THREAD

**Issue by triqi** [DianaIonita/serverless-api-gateway-caching#27]
## Summary
Declaring a HTTP event using the shorthand notation produces an error.

Example
```
lambda:
  handler: src/lambda.handler
  events:
    - http: get /users
```

## Debug output
```
Type Error ---------------------------------------------

  Cannot read property 'toUpperCase' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

Stack Trace --------------------------------------------

TypeError: Cannot read property 'toUpperCase' of undefined
    at createPatchForEndpoint (/<project root>/node_modules/serverless-api-gateway-caching/src/stageCache.js:88:14)
    at updateStageCacheSettings (/<project root>/node_modules/serverless-api-gateway-caching/src/stageCache.js:128:25)
From previous event:
    at PluginManager.invoke (/<project root>/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/<project root>/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/<project root>/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/<project root>/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/<project root>/node_modules/serverless/bin/serverless:42:50)
```

**Comment by DianaIonita** [comment]
Hi @triqi,

Thanks for pointing this out. I've released [v1.3.1](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.3.1) which now supports http events defined in shorthand. Please note that caching is disabled for such functions, because to enable it you need to explicitly say `caching: enabled` under event settings.
Please reopen this ticket if you find any issues with it.
