### ISSUE TITLE
Cannot read property 'cachingEnabled' of undefined

### ISSUE THREAD

**Issue by triqi** [DianaIonita/serverless-api-gateway-caching#37]
# Summary
A two step deployment throws an exception `Cannot read property 'cachingEnabled' of undefined`. This is likely due to the `this.settings` not being initialised during the deploy step.

## Steps to reproduce
1. `serverless package`
2. `serverless deploy --package ./.serverless`

## Stack trace

Type Error ---------------------------------------------

  Cannot read property 'cachingEnabled' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'cachingEnabled' of undefined
    at updateStageCacheSettings (/Project Root/node_modules/serverless-api-gateway-caching/src/stageCache.js:133:16)
    at ApiGatewayCachingPlugin.updateStage (/Project Root/node_modules/serverless-api-gateway-caching/src/apiGatewayCachingPlugin.js:47:12)
    at BbPromise.reduce (/Project Root/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Project Root/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/Project Root/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/Project Root/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Project Root/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Project Root/node_modules/serverless/bin/serverless:44:28)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.14.1
     Serverless Version:     1.34.0

**Comment by DianaIonita** [comment]
Cheers @triqi - I just released [v1.3.3](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.3.3) which fixes this.

**Comment by triqi** [comment]
> Cheers @triqi - I just released [v1.3.3](https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.3.3) which fixes this.

Thanks @DianaIonita.
